Iter13
Zagir2000/alert pull request #13
Opened 2023-06-12 09:23 UTC by Zagir2000

2023-06-15 20:00 UTC, arttet requested changes
Please add indexes to the database schema and fix linter errors

2023-06-15 20:00 UTC, arttet commented on internal/server/handlers/handlers.go
> +		var jsonMetrics models.Metrics
jsonMetrics := &models.Metrics{}

2023-06-15 20:00 UTC, arttet commented on internal/server/handlers/handlers.go
> +	pingFn := func(res http.ResponseWriter, req *http.Request) {
```
	return func(res http.ResponseWriter, req *http.Request) {
		if req.Method != http.MethodGet {
			m.log.Debug("got request with bad method", zap.String("method", req.Method))
			return
		}
		ctx, cancel := context.WithTimeout(ctx, 2*time.Second)
		defer cancel()
		if err := m.pgDB.PingDB(ctx); err != nil {
			res.WriteHeader(http.StatusInternalServerError)
		} else {
			res.WriteHeader(http.StatusOK)
		}
		_, err := res.Write([]byte("pong"))
		if err != nil {
			return
		}
	}
```

2023-06-15 20:00 UTC, arttet commented on internal/server/storage/db.go
> +	ID TEXT UNIQUE,
Please add indexes

2023-06-15 20:00 UTC, arttet commented on internal/server/storage/db.go
> +const query = `CREATE TABLE IF NOT EXISTS Metrics (
It looks like schema.

2023-06-16 06:28 UTC, Zagir2000 commented on internal/server/handlers/handlers.go
> +	pingFn := func(res http.ResponseWriter, req *http.Request) {
Ты просто в прошлый раз говорил, не использовать анонимных функций, поэтому я решил сделать так

2023-06-18 12:58 UTC, arttet approved these changes

2023-06-18 12:58 UTC, arttet commented on internal/server/handlers/router.go
> +	zapNewLogger := logger.NewZapLoggerStruct(newHandStruct.log)
It would be better if you use a logger as a parameter of the function.

2023-06-18 12:58 UTC, arttet commented on postgresdb/migrations/0001_init.up.sql
> +        ID TEXT UNIQUE,
```
            id INT GENERATED ALWAYS AS IDENTITY,
            mname TEXT NOT NULL,
            mtype TEXT NOT NULL,


            PRIMARY KEY(id),
            UNIQUE(mname, mtype)
``

2023-06-19 16:29 UTC, merged